name: "Remove Your Information"
description: "Request the removal of your profile from our static website directory using your username."
title: "[Removal Request]: BTC2Free"
labels: ["pending-review"]

body:
  - type: input
    id: username
    attributes:
      label: Freecycle Username to Remove
      placeholder: "Enter just your username (letters, numbers, + and - symbols allowed)."
    validations:
      required: true
