name: Remove Your Information
description: Request removal of your profile from the BTC2Free directory.
title: "[Removal Request]: BTC2Free"
labels: ["pending"]

body:
  - type: input
    id: username
    attributes:
      label: Freecycle Username
      description: "Enter ONLY your username, not a full URL."
      placeholder: "your_username"
    validations:
      required: true
