name: Submit Your Information
description: Fill out this form with your Freecycle profile & Bitcoin address to be added to this website.
title: "[Submission]: BTC2Free"
labels: ["pending-review"] 
body:
  - type: input
    id: username
    attributes:
        label: Freecycle Username
    validations:
      required: true

  - type: input
    id: bitcoin_address
    attributes:
      label: Bitcoin Address
      description: "Provide a valid Legacy (1...), Nested SegWit (3...), or Native SegWit (bc1...) address."
      placeholder: "e.g., bc1qxy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh"
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: "Privacy Policy"
      options:
        - label: "I agree to publish this information publicly on the website & use the Remove My Entry button to request removal, if desired."
          required: true
