name: Process Website Directory

on:
  issues:
    types: [labeled]

jobs:
  update-data:
    if: github.event.label.name == 'approved'
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'

      - name: Parse Submission Form
        id: parse_add
        uses: stefanbuck/github-issue-parser@v3
        with:
          template-path: .github/ISSUE_TEMPLATE/submit-info.yml

      - name: Process Directory Changes
        run: node scripts/process-directory.js
        env:
          ADD_USERNAME: ${{ steps.parse_add.outputs.issueparser_username }}
          BTC: ${{ steps.parse_add.outputs.issueparser_bitcoin_address }}
          REMOVE_USERNAME: ${{ github.event.issue.body }}

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data.json

          if git diff --staged --quiet; then
            echo "No changes"
            exit 0
          fi

          git commit -m "Update website directory"
          git push origin HEAD:${{ github.ref_name }}

      - name: Clean Up and Close Issue
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "closed"
            });
